host: localhost
listening-ip: "127.0.0.1" #Leave out if you want to listen on 0.0.0.0
grpcPort: 8081
proxyPort: 8082


auth-key: agent-auth-key
sign-key: agent-sign-key
max-workers: 5
file-transfer-root: /path/to/desired/filetransfer/root
ova-dir: /path/to/desired/ova/directory
state-path: /path/to/desired/state/directory

vpn-service:
  endpoint: vpn.localhost
  port: 5353
  auth-key: vpn-service-auth-key
  sign-key: vpn-service-sign-key
  wg-conf-dir: /etc/wireguard
  tls-enabled: false

docker-repositories:
- username: username
  password: password
  serveraddress: registry.gitlab.com